#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

build_dir="${WORKSPACE:-${script_dir}/_build}"
install_dir="${WORKSPACE:-${script_dir}/_install}"

export CC="${CC:-clang}"
export CXX="${CXX:-clang++}"

if [ ! -f "${build_dir}/build.ninja" ] ; then
    cmake -S "${script_dir}" -B "${build_dir}" -G "Ninja" -DCMAKE_INSTALL_PREFIX=${install_dir}
fi

cmake --build "${build_dir}" --target all
cmake --build "${build_dir}" --target build-ui

ctest --test-dir "${build_dir}" --verbose
